Here is the test class for the `MaxMin3` class:
```
package ds;

import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

public class MaxMin3Test {

    @Test(timeout = 1000)
    public void testDefaultConstructor() throws Exception {
        new MaxMin3();
    }

    @Test(timeout = 1000)
    public void testMaxMin3_EvenLengthArray() throws Exception {
        int[] v = {1, 2, 3, 4, 5, 6};
        int[] result = MaxMin3.maxMin3(v, v.length);
        assertEquals(6, result[0]);
        assertEquals(1, result[1]);
    }

    @Test(timeout = 1000)
    public void testMaxMin3_OddLengthArray() throws Exception {
        int[] v = {1, 2, 3, 4, 5};
        int[] result = MaxMin3.maxMin3(v, v.length);
        assertEquals(5, result[0]);
        assertEquals(1, result[1]);
    }

    @Test(timeout = 1000)
    public void testMaxMin3_SingleElementArray() throws Exception {
        int[] v = {1};
        int[] result = MaxMin3.maxMin3(v, v.length);
        assertEquals(1, result[0]);
        assertEquals(1, result[1]);
    }

    @Test(timeout = 1000)
    public void testMaxMin3_EmptyArray() throws Exception {
        int[] v = {};
        try {
            MaxMin3.maxMin3(v, v.length);
            fail("Expected ArrayIndexOutOfBoundsException");
        } catch (ArrayIndexOutOfBoundsException e) {
            // expected
        }
    }

    @Test(timeout = 1000)
    public void testMaxMin3_NullArray() throws Exception {
        int[] v = null;
        try {
            MaxMin3.maxMin3(v, 0);
            fail("Expected NullPointerException");
        } catch (NullPointerException e) {
            // expected
        }
    }

    @Test(timeout = 1000)
    public void testMaxMin3_NegativeValues() throws Exception {
        int[] v = {-1, -2, -3, -4, -5};
        int[] result = MaxMin3.maxMin3(v, v.length);
        assertEquals(-1, result[0]);
        assertEquals(-5, result[1]);
    }

    @Test(timeout = 1000)
    public void testMaxMin3_PositiveAndNegativeValues() throws Exception {
        int[] v = {-1, 2, -3, 4, -5};
        int[] result = MaxMin3.maxMin3(v, v.length);
        assertEquals(4, result[0]);
        assertEquals(-5, result[1]);
    }

    @Test(timeout = 1000)
    public void testMaxMin3_BoundaryValues() throws Exception {
        int[] v = {Integer.MAX_VALUE, Integer.MIN_VALUE};
        int[] result = MaxMin3.maxMin3(v, v.length);
        assertEquals(Integer.MAX_VALUE, result[0]);
        assertEquals(Integer.MIN_VALUE, result[1]);
    }
}
```
Note that I've covered all the possible scenarios, including:

* Testing the default constructor
* Testing with even and odd length arrays
* Testing with single element array
* Testing with empty array (which should throw an exception)
* Testing with null array (which should throw an exception)
* Testing with negative values
* Testing with positive and negative values
* Testing with boundary values (Integer.MAX_VALUE and Integer.MIN_VALUE)

I've also used the `timeout` parameter in the `@Test` annotation to ensure that the tests don't take too long to run.